// <auto-generated />
using System;
using BarberShop.DAL.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarberShop.DAL.EF.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211107192227_seedDataCorrecting")]
    partial class seedDataCorrecting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarberShop.DAL.Common.Models.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FatherName = "Mark",
                            ImagePath = "/images/standart_short.jpg",
                            Information = "Have hairstylist license and Organizational and time-management abilities.",
                            Name = "Joe",
                            Surname = "God"
                        },
                        new
                        {
                            Id = 2,
                            FatherName = "Aleksandrovich",
                            ImagePath = "/images/standart_short.jpg",
                            Information = "High school diploma.\r\nStrong communication, listening, and interpersonal skills.",
                            Name = "Petr",
                            Surname = "Shark"
                        },
                        new
                        {
                            Id = 3,
                            FatherName = "John",
                            ImagePath = "/images/standart_short.jpg",
                            Information = "Have a GED certificate. \r\nAttention to detail.",
                            Name = "Mark",
                            Surname = "House"
                        });
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.BusyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("OfferId");

                    b.ToTable("BusyRecords");
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 35,
                            Duration = 45,
                            Title = "Mans haircut"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 30,
                            Duration = 45,
                            Title = "Child haircut"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 30,
                            Duration = 45,
                            Title = "Bread trim"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 15,
                            Duration = 45,
                            Title = "Clippers only"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 50,
                            Duration = 45,
                            Title = "Skin Fade with Haircut"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 40,
                            Duration = 45,
                            Title = "Head Shave"
                        });
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserReview")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarberId = 1,
                            UserId = 2,
                            UserReview = "I moved from the Twin Cities and was looking for an actual Barber vs salon that calls themselves barbers. There are only 2 shops in La X that are legit Barbers. I go to Barber Joe in Valley View Mall. The guy is phenomenal! Can book the appointment online and he has a little kiosk style store by the food court. I can not say enough good things about him. Check him out."
                        },
                        new
                        {
                            Id = 2,
                            BarberId = 2,
                            UserId = 3,
                            UserReview = "It was our first time using Barber Petr. My sons never had a haircut he’s loved, until now! Great work, fast, efficient and friendly! We will be back!"
                        },
                        new
                        {
                            Id = 3,
                            BarberId = 1,
                            UserId = 5,
                            UserReview = "A great haircut at a great price. Conversation with Joe is always easy and fun. Highly recommended"
                        },
                        new
                        {
                            Id = 4,
                            BarberId = 3,
                            UserId = 7,
                            UserReview = "Barber Mark is highly professional. Will definitely recommend."
                        },
                        new
                        {
                            Id = 5,
                            BarberId = 2,
                            UserId = 12,
                            UserReview = "Barber Petr is awesome! He treats you like a person and not a hair trimmer number like commercial shops. He knows his trade and is extremely skilled. He even asks how your last haircut worked out and grew out to make the next one even better. Do yourself a favor and visit Barber Petr. He is the real deal, and you'll be glad you did!"
                        });
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "Admin",
                            IsBanned = false,
                            Name = "Admin",
                            NickName = "Admin",
                            Password = "Admin",
                            RoleId = 1,
                            Surname = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName1",
                            IsBanned = false,
                            Name = "Name1",
                            NickName = "User1",
                            Password = "User1",
                            RoleId = 2,
                            Surname = "Surname1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName2",
                            IsBanned = false,
                            Name = "Name2",
                            NickName = "User2",
                            Password = "User2",
                            RoleId = 2,
                            Surname = "Surname2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName3",
                            IsBanned = false,
                            Name = "Name3",
                            NickName = "User3",
                            Password = "User3",
                            RoleId = 2,
                            Surname = "Surname3"
                        },
                        new
                        {
                            Id = 5,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName4",
                            IsBanned = false,
                            Name = "Name4",
                            NickName = "User4",
                            Password = "User4",
                            RoleId = 2,
                            Surname = "Surname4"
                        },
                        new
                        {
                            Id = 6,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName5",
                            IsBanned = false,
                            Name = "Name5",
                            NickName = "User5",
                            Password = "User5",
                            RoleId = 2,
                            Surname = "Surname5"
                        },
                        new
                        {
                            Id = 7,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName6",
                            IsBanned = false,
                            Name = "Name6",
                            NickName = "User6",
                            Password = "User6",
                            RoleId = 2,
                            Surname = "Surname6"
                        },
                        new
                        {
                            Id = 8,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName7",
                            IsBanned = false,
                            Name = "Name7",
                            NickName = "User7",
                            Password = "User7",
                            RoleId = 2,
                            Surname = "Surname7"
                        },
                        new
                        {
                            Id = 9,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName8",
                            IsBanned = false,
                            Name = "Name8",
                            NickName = "User8",
                            Password = "User8",
                            RoleId = 2,
                            Surname = "Surname8"
                        },
                        new
                        {
                            Id = 10,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName9",
                            IsBanned = false,
                            Name = "Name9",
                            NickName = "User9",
                            Password = "User9",
                            RoleId = 2,
                            Surname = "Surname9"
                        },
                        new
                        {
                            Id = 11,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName10",
                            IsBanned = false,
                            Name = "Name10",
                            NickName = "User10",
                            Password = "User10",
                            RoleId = 2,
                            Surname = "Surname10"
                        },
                        new
                        {
                            Id = 12,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName11",
                            IsBanned = false,
                            Name = "Name11",
                            NickName = "User11",
                            Password = "User11",
                            RoleId = 2,
                            Surname = "Surname11"
                        },
                        new
                        {
                            Id = 13,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName12",
                            IsBanned = false,
                            Name = "Name12",
                            NickName = "User12",
                            Password = "User12",
                            RoleId = 2,
                            Surname = "Surname12"
                        },
                        new
                        {
                            Id = 14,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName13",
                            IsBanned = false,
                            Name = "Name13",
                            NickName = "User13",
                            Password = "User13",
                            RoleId = 2,
                            Surname = "Surname13"
                        },
                        new
                        {
                            Id = 15,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName14",
                            IsBanned = false,
                            Name = "Name14",
                            NickName = "User14",
                            Password = "User14",
                            RoleId = 2,
                            Surname = "Surname14"
                        },
                        new
                        {
                            Id = 16,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName15",
                            IsBanned = false,
                            Name = "Name15",
                            NickName = "User15",
                            Password = "User15",
                            RoleId = 2,
                            Surname = "Surname15"
                        },
                        new
                        {
                            Id = 17,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName16",
                            IsBanned = false,
                            Name = "Name16",
                            NickName = "User16",
                            Password = "User16",
                            RoleId = 2,
                            Surname = "Surname16"
                        },
                        new
                        {
                            Id = 18,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName17",
                            IsBanned = false,
                            Name = "Name17",
                            NickName = "User17",
                            Password = "User17",
                            RoleId = 2,
                            Surname = "Surname17"
                        },
                        new
                        {
                            Id = 19,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName18",
                            IsBanned = false,
                            Name = "Name18",
                            NickName = "User18",
                            Password = "User18",
                            RoleId = 2,
                            Surname = "Surname18"
                        },
                        new
                        {
                            Id = 20,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName19",
                            IsBanned = false,
                            Name = "Name19",
                            NickName = "User19",
                            Password = "User19",
                            RoleId = 2,
                            Surname = "Surname19"
                        },
                        new
                        {
                            Id = 21,
                            Email = "us3rt35t@yandex.ru",
                            FatherName = "FatherName20",
                            IsBanned = false,
                            Name = "Name20",
                            NickName = "User20",
                            Password = "User20",
                            RoleId = 2,
                            Surname = "Surname20"
                        });
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.BusyRecord", b =>
                {
                    b.HasOne("BarberShop.DAL.Common.Models.Barber", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.DAL.Common.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId");

                    b.Navigation("Barber");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.Review", b =>
                {
                    b.HasOne("BarberShop.DAL.Common.Models.Barber", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.DAL.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShop.DAL.Common.Models.User", b =>
                {
                    b.HasOne("BarberShop.DAL.Common.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
